pipeline:
  agent:
    any: 
  stages:
    - stage: "Deploy"
      steps:
        script:
          - withCredentials([azureServicePrincipal('AzureServicePrincipleCredentials')]) {
                powershell '''
                   az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
                   az account set -s $AZURE_SUBSCRIPTION_ID
                   az resource list
                   //az resource list --name 'resourceName'
                '''
